[package]
name = "ttc-trainbenchmark-adapton"
version = "0.0.1"
authors = ["Georg Hinkel <hinkel@fzi.de>"]
license = "MIT"
description = "An implementation of the TTC 2015 Train Benchmark in Rust"

[[bin]]
name = "ttc-trainbenchmark"
path = "src/main.rs"

[dependencies]
bitflags = ">=0.5, <0.8"
xml-rs = "0.3.5"
adapton = "0.2.4"
regex = "0.2"
lazy_static = "0.2.2"